version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5555:5432'
    volumes:
      - ./data:/usr/apps/deck-api/data
